### ISSUE TITLE
Unable to contact, ask for help

### ISSUE THREAD

**Issue by hhtqaq** [pjfanning/excel-streaming-reader-sample#1]
I need to convert pptx to pictures, but when using poi, the chart data will be lost and cannot be converted to pictures. How to solve it

**Comment by pjfanning** [comment]
this project is for excel only - does not support powerpoint

**Comment by hhtqaq** [comment]
I know, but I can’t find anyone in all the repositories to solve this problem. It’s too difficult, so I ask for help.
