### ISSUE TITLE
FormulaEvaluator is not supported for xlsx files.

### ISSUE THREAD

**Issue by vikasrathee-cs** [pjfanning/excel-streaming-reader-sample#2]
FormulaEvaluator is not supported for xlsx files.

workbook.getCreationHelper() throws Method not supported exception.

**Comment by pjfanning** [comment]
You can't evaluate formulas in a streaming way - the formula could relate to a cell in a different sheet or a different part of a sheet.
Streaming means only having a very small part of the data in memory at a given time.
excel-streaming-reader reads the resolved values that are stored in the xlsx cell data so it does not need to use the FormulaEvaluator anyway.

**Comment by pjfanning** [comment]
You might want to read https://github.com/pjfanning/excel-streaming-reader/issues/191

I am going to close the ability to create issues in this repo. https://github.com/pjfanning/excel-streaming-reader will still have an issues and discussions tabs.
